# Generated by Django 3.2.7 on 2021-09-14 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blog_blogtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='blog_tags', to='users.BlogTag'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Blog content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Blog title'),
        ),
    ]
