# Generated by Django 3.2.7 on 2021-09-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210914_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
    ]
